services:
  - type: web
    name: fullstack-eshop
    env: node
    plan: free
    buildCommand: |
      npm --prefix server install
      npm --prefix client install
      npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URL
        sync: false
      - key: JWT_SECRET
        sync: false
